name = "QuantumAlgebra"
uuid = "1b9008d5-2a9d-4901-8cfb-44bb87795b64"
version = "1.5.1"
authors = ["Johannes Feist <johannes.feist@gmail.com> and contributors"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[weakdeps]
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
SymPyPythonCall = "bc8888f7-b21e-4b7c-a06a-5d9c9496438c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
QuantumAlgebraSymPyExt = "SymPy"
QuantumAlgebraSymPyPythonCallExt = "SymPyPythonCall"
QuantumAlgebraSymbolicsExt = "Symbolics"

[compat]
Combinatorics = "1"
LaTeXStrings = "1.3"
Latexify = "0.16.6"
OrderedCollections = "1.4"
PackageExtensionCompat = "1"
PrecompileTools = "1"
Preferences = "1"
SymPy = "1, 2"
SymPyPythonCall = "0.3, 0.4, 0.5"
Symbolics = "5.14, 6, 7"
julia = "1.6"

[extras]
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
SymPyPythonCall = "bc8888f7-b21e-4b7c-a06a-5d9c9496438c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
